Greedy agent
YetAnotherSpieskowcy/Carcassonne-Neural-Network pull request #7
Opened 2024-09-22 10:24 UTC by BognaLew

2024-09-27 14:26 UTC, bstrzelecki submitted a review, later dismissed

2024-09-29 08:23 UTC, Jackenmen requested changes

2024-09-29 08:23 UTC, Jackenmen commented on src/agents/greedy.py
> +        self.ID = id
This should be `id` per the naming convention for attributes used in our Python projects.
```suggestion
        self.id = id
```

2024-09-29 08:23 UTC, Jackenmen commented on src/agents/greedy.py
> +        Action is assigned it's point value.
```suggestion
        Action is assigned its point value.
```

2024-09-29 08:23 UTC, Jackenmen commented on src/agents/greedy.py
> +        Action is assigned it's point value.
```suggestion
        Action is assigned its point value.
```

2024-09-30 17:46 UTC, Jackenmen approved these changes

2024-10-06 17:25 UTC, bstrzelecki approved these changes

2024-10-10 17:36 UTC, merged